version: "3.3"

services:
  kibana-auth-proxy:
    image: quay.io/wasilak/elastauth:1.0.7
    command:
      - /elastauth
      - --config=/app/
    expose:
      - 3000
    ports:
      - "8083:3000"
    volumes:
      - "./config.yml:/app/config.yml"
    depends_on:
      - traefik
      - authelia
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`kibana-auth-proxy.127-0-0-1.nip.io`)'
      - 'traefik.http.routers.api.entryPoints=https'
      - 'traefik.http.routers.api.tls=true'

  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: unless-stopped
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--pilot.dashboard=false'
      - '--global.sendAnonymousUsage=false'
      - '--global.checkNewVersion=false'
      - '--log=true'
      - '--log.level=DEBUG'
      - '--log.filepath=/config/traefik.log'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entryPoints.http=true'
      - '--entryPoints.http.address=:80/tcp'
      - '--entryPoints.https.address=:443/tcp'
      - '--entryPoints.http.forwardedHeaders.insecure=true'
      - '--entryPoints.http.proxyProtocol.insecure=true'
    ports:
      - "8080:80"
      - "4343:443"
      - "8081:8080"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data/traefik:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`traefik.127-0-0-1.nip.io`)'
      - 'traefik.http.routers.api.entryPoints=http'
      # - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.service=api@internal'
      # - 'traefik.http.routers.api.middlewares=authelia@docker'

  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    volumes:
      - ${PWD}/data/authelia/config:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.127-0-0-1.nip.io`)'
      - 'traefik.http.routers.authelia.entryPoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.127-0-0-1.nip.io:4343/'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'

      - 'traefik.http.middlewares.authelia-chain.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.127-0-0-1.nip.io:4343/'
      - 'traefik.http.middlewares.authelia-chain.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-chain.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'

      # - 'traefik.http.middlewares.kibana-auth-proxy.forwardauth.address=https://kibana-auth-proxy.127-0-0-1.nip.io:4334'
      - 'traefik.http.middlewares.kibana-auth-proxy.forwardauth.address=http://kibana-auth-proxy:3000/'
      - 'traefik.http.middlewares.kibana-auth-proxy.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-chain.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email,Authorization'
      # - 'traefik.http.middlewares.authelia-basic.forwardAuth.address=http://authelia:9091/api/verify?auth=basic'
      # - 'traefik.http.middlewares.authelia-basic.forwardAuth.trustForwardHeader=true'
      # - 'traefik.http.middlewares.authelia-basic.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'

      - 'traefik.http.middlewares.auth-combined.chain.middlewares=authelia-chain,kibana-auth-proxy'
    depends_on:
      - traefik

  hello-world:
    image: quay.io/wasilak/go-hello-world:0.0.7
    command:
      - /usr/local/bin/go-hello-world
      - -listen-addr=0.0.0.0:3000
    expose:
      - 3000
    ports:
      - "8085:3000"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.go-hello-world.rule=Host(`go-hello-world.127-0-0-1.nip.io`)'
      - 'traefik.http.routers.go-hello-world.entryPoints=https'
      - 'traefik.http.routers.go-hello-world.tls=true'
      # - 'traefik.http.routers.go-hello-world.middlewares=authelia@docker'
      - 'traefik.http.routers.go-hello-world.middlewares=auth-combined@docker'
