version: "3.3"

services:
  kibana-auth-proxy:
    # build: .
    image: quay.io/wasilak/elastauth:1.0.7
    env_file: ../.env
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - "../config.yml:/app/config.yml"

  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: unless-stopped
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--pilot.dashboard=false'
      - '--global.sendAnonymousUsage=false'
      - '--global.checkNewVersion=false'
      - '--log=true'
      - '--log.level=DEBUG'
      - '--log.filepath=/config/traefik.log'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entryPoints.http=true'
      - '--entryPoints.http.address=:80/tcp'
      - '--entryPoints.http.forwardedHeaders.insecure=true'
      - '--entryPoints.http.proxyProtocol.insecure=true'
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data/traefik:/config
    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.api.rule=Host(`traefik.example.com`)'
    #   - 'traefik.http.routers.api.entryPoints=http'
    #   - 'traefik.http.routers.api.tls=true'
    #   - 'traefik.http.routers.api.service=api@internal'
    #   - 'traefik.http.routers.api.middlewares=authelia@docker'

  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    expose:
      - 9091
    volumes:
      - ${PWD}/data/authelia/config:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.127-0-0-1.nip.io`)'
      - 'traefik.http.routers.authelia.entryPoints=http'
      - 'traefik.http.routers.authelia.tls=false'
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.example.com%2F'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      - 'traefik.http.middlewares.authelia-basic.forwardAuth.address=http://authelia:9091/api/verify?auth=basic'
      - 'traefik.http.middlewares.authelia-basic.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-basic.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
