default_roles:
  - your_default_kibana_role
group_mappings:
  your_ad_group:
    - your_kibana_role
headers:
  username: Remote-User
  groups: Remote-Groups
  email: Remote-Email
  name: Remote-Name
log_level: info
log_format: json
